### ISSUE TITLE
Fails on install using per-project npmrc file

### ISSUE THREAD

**Issue by andersonba** [scott113341/npm-install-version#25]
I use a custom npm registry per project, so, we stored the `.npmrc` file inside of the project folder.

`niv` doesn't install using my registry because the current path of spawn process is `node_modules/.npm-install-version-temp` (https://github.com/scott113341/npm-install-version/blob/master/src/install.js#L32), therefore, niv ignore my npmrc file and all private packages aren't installed.

**Comment by scott113341** [comment]
Thank you!  Fixed in `6.0.1`
